//
// AlertRule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AlertRule: Codable, JSONEncodable, Hashable {

    public enum Condition: String, Codable, CaseIterable {
        case failureRate = "failure_rate"
        case latency = "latency"
        case consecutiveFailures = "consecutive_failures"
    }
    public enum Channels: String, Codable, CaseIterable {
        case slack = "slack"
        case email = "email"
        case webhook = "webhook"
    }
    public var id: UUID?
    public var name: String?
    public var condition: Condition?
    public var threshold: Int?
    public var channels: [Channels]?
    public var isActive: Bool?
    public var createdAt: String?

    public init(id: UUID? = nil, name: String? = nil, condition: Condition? = nil, threshold: Int? = nil, channels: [Channels]? = nil, isActive: Bool? = nil, createdAt: String? = nil) {
        self.id = id
        self.name = name
        self.condition = condition
        self.threshold = threshold
        self.channels = channels
        self.isActive = isActive
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case condition
        case threshold
        case channels
        case isActive = "is_active"
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(condition, forKey: .condition)
        try container.encodeIfPresent(threshold, forKey: .threshold)
        try container.encodeIfPresent(channels, forKey: .channels)
        try container.encodeIfPresent(isActive, forKey: .isActive)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension AlertRule: Identifiable {}
