//
// ApiKeyInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ApiKeyInfo: Codable, JSONEncodable, Hashable {

    public var id: UUID?
    /** Masked key prefix (e.g. \"hs_abc1...\") */
    public var _prefix: String?
    public var createdAt: String?
    public var lastUsedAt: String?
    public var isActive: Bool?

    public init(id: UUID? = nil, _prefix: String? = nil, createdAt: String? = nil, lastUsedAt: String? = nil, isActive: Bool? = nil) {
        self.id = id
        self._prefix = _prefix
        self.createdAt = createdAt
        self.lastUsedAt = lastUsedAt
        self.isActive = isActive
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case _prefix = "prefix"
        case createdAt = "created_at"
        case lastUsedAt = "last_used_at"
        case isActive = "is_active"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(_prefix, forKey: ._prefix)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(lastUsedAt, forKey: .lastUsedAt)
        try container.encodeIfPresent(isActive, forKey: .isActive)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ApiKeyInfo: Identifiable {}
