//
// Auth2faEnablePost200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Auth2faEnablePost200Response: Codable, JSONEncodable, Hashable {

    public var secret: String?
    public var qrUrl: String?

    public init(secret: String? = nil, qrUrl: String? = nil) {
        self.secret = secret
        self.qrUrl = qrUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case secret
        case qrUrl = "qr_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(secret, forKey: .secret)
        try container.encodeIfPresent(qrUrl, forKey: .qrUrl)
    }
}

