//
// Confirm2faRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Confirm2faRequest: Codable, JSONEncodable, Hashable {

    public static let codeRule = StringRule(minLength: 6, maxLength: 6, pattern: nil)
    public var code: String

    public init(code: String) {
        self.code = code
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(code, forKey: .code)
    }
}

