//
// ContactRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ContactRequest: Codable, JSONEncodable, Hashable {

    public var name: String
    public var email: String
    public var subject: String
    public var message: String

    public init(name: String, email: String, subject: String, message: String) {
        self.name = name
        self.email = email
        self.subject = subject
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case email
        case subject
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(email, forKey: .email)
        try container.encode(subject, forKey: .subject)
        try container.encode(message, forKey: .message)
    }
}

