//
// CreateAlertRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateAlertRequest: Codable, JSONEncodable, Hashable {

    public enum Condition: String, Codable, CaseIterable {
        case failureRate = "failure_rate"
        case latency = "latency"
        case consecutiveFailures = "consecutive_failures"
    }
    public var name: String
    public var condition: Condition
    public var threshold: Int
    public var channels: [String]
    public var endpointId: UUID?

    public init(name: String, condition: Condition, threshold: Int, channels: [String], endpointId: UUID? = nil) {
        self.name = name
        self.condition = condition
        self.threshold = threshold
        self.channels = channels
        self.endpointId = endpointId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case condition
        case threshold
        case channels
        case endpointId = "endpoint_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(condition, forKey: .condition)
        try container.encode(threshold, forKey: .threshold)
        try container.encode(channels, forKey: .channels)
        try container.encodeIfPresent(endpointId, forKey: .endpointId)
    }
}

