//
// CreateApiKeyResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateApiKeyResponse: Codable, JSONEncodable, Hashable {

    public var id: UUID?
    /** Full API key — only shown once */
    public var key: String?
    public var _prefix: String?
    public var message: String?

    public init(id: UUID? = nil, key: String? = nil, _prefix: String? = nil, message: String? = nil) {
        self.id = id
        self.key = key
        self._prefix = _prefix
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case key
        case _prefix = "prefix"
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(key, forKey: .key)
        try container.encodeIfPresent(_prefix, forKey: ._prefix)
        try container.encodeIfPresent(message, forKey: .message)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension CreateApiKeyResponse: Identifiable {}
