//
// CreateWebhookRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateWebhookRequest: Codable, JSONEncodable, Hashable {

    public var endpointId: UUID
    /** Event type (e.g. \"order.created\") */
    public var event: String?
    /** Webhook payload */
    public var data: AnyCodable

    public init(endpointId: UUID, event: String? = nil, data: AnyCodable) {
        self.endpointId = endpointId
        self.event = event
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case endpointId = "endpoint_id"
        case event
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(endpointId, forKey: .endpointId)
        try container.encodeIfPresent(event, forKey: .event)
        try container.encode(data, forKey: .data)
    }
}

