//
// CreateTransformRuleRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateTransformRuleRequest: Codable, JSONEncodable, Hashable {

    public var name: String
    public var ruleType: String
    public var config: AnyCodable

    public init(name: String, ruleType: String, config: AnyCodable) {
        self.name = name
        self.ruleType = ruleType
        self.config = config
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case ruleType = "rule_type"
        case config
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(ruleType, forKey: .ruleType)
        try container.encode(config, forKey: .config)
    }
}

