//
// CustomDomainsPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CustomDomainsPostRequest: Codable, JSONEncodable, Hashable {

    public var domain: String?

    public init(domain: String? = nil) {
        self.domain = domain
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case domain
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(domain, forKey: .domain)
    }
}

