//
// Endpoint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Endpoint: Codable, JSONEncodable, Hashable {

    public enum RoutingStrategy: String, Codable, CaseIterable {
        case roundRobin = "round-robin"
        case latency = "latency"
        case failover = "failover"
    }
    public enum Format: String, Codable, CaseIterable {
        case standard = "standard"
        case cloudevents = "cloudevents"
    }
    public var id: UUID?
    public var url: String?
    public var description: String?
    public var isActive: Bool?
    public var retryPolicy: RetryPolicy?
    public var createdAt: Date?
    /** CIDR blocks or exact IPs */
    public var allowedIps: [String]?
    /** Wildcard patterns (e.g. \"order.*\") */
    public var eventFilter: [String]?
    public var customHeaders: AnyCodable?
    public var routingStrategy: RoutingStrategy?
    public var fallbackUrl: String?
    public var avgResponseMs: Int?
    public var failureStreak: Int?
    public var format: Format?

    public init(id: UUID? = nil, url: String? = nil, description: String? = nil, isActive: Bool? = nil, retryPolicy: RetryPolicy? = nil, createdAt: Date? = nil, allowedIps: [String]? = nil, eventFilter: [String]? = nil, customHeaders: AnyCodable? = nil, routingStrategy: RoutingStrategy? = nil, fallbackUrl: String? = nil, avgResponseMs: Int? = nil, failureStreak: Int? = nil, format: Format? = nil) {
        self.id = id
        self.url = url
        self.description = description
        self.isActive = isActive
        self.retryPolicy = retryPolicy
        self.createdAt = createdAt
        self.allowedIps = allowedIps
        self.eventFilter = eventFilter
        self.customHeaders = customHeaders
        self.routingStrategy = routingStrategy
        self.fallbackUrl = fallbackUrl
        self.avgResponseMs = avgResponseMs
        self.failureStreak = failureStreak
        self.format = format
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case url
        case description
        case isActive = "is_active"
        case retryPolicy = "retry_policy"
        case createdAt = "created_at"
        case allowedIps = "allowed_ips"
        case eventFilter = "event_filter"
        case customHeaders = "custom_headers"
        case routingStrategy = "routing_strategy"
        case fallbackUrl = "fallback_url"
        case avgResponseMs = "avg_response_ms"
        case failureStreak = "failure_streak"
        case format
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(isActive, forKey: .isActive)
        try container.encodeIfPresent(retryPolicy, forKey: .retryPolicy)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(allowedIps, forKey: .allowedIps)
        try container.encodeIfPresent(eventFilter, forKey: .eventFilter)
        try container.encodeIfPresent(customHeaders, forKey: .customHeaders)
        try container.encodeIfPresent(routingStrategy, forKey: .routingStrategy)
        try container.encodeIfPresent(fallbackUrl, forKey: .fallbackUrl)
        try container.encodeIfPresent(avgResponseMs, forKey: .avgResponseMs)
        try container.encodeIfPresent(failureStreak, forKey: .failureStreak)
        try container.encodeIfPresent(format, forKey: .format)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Endpoint: Identifiable {}
