//
// EndpointHealth.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EndpointHealth: Codable, JSONEncodable, Hashable {

    public var endpointId: UUID?
    public var isHealthy: Bool?
    public var failureStreak: Int?
    public var avgResponseMs: Int?
    public var lastFailureAt: Date?

    public init(endpointId: UUID? = nil, isHealthy: Bool? = nil, failureStreak: Int? = nil, avgResponseMs: Int? = nil, lastFailureAt: Date? = nil) {
        self.endpointId = endpointId
        self.isHealthy = isHealthy
        self.failureStreak = failureStreak
        self.avgResponseMs = avgResponseMs
        self.lastFailureAt = lastFailureAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case endpointId = "endpoint_id"
        case isHealthy = "is_healthy"
        case failureStreak = "failure_streak"
        case avgResponseMs = "avg_response_ms"
        case lastFailureAt = "last_failure_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(endpointId, forKey: .endpointId)
        try container.encodeIfPresent(isHealthy, forKey: .isHealthy)
        try container.encodeIfPresent(failureStreak, forKey: .failureStreak)
        try container.encodeIfPresent(avgResponseMs, forKey: .avgResponseMs)
        try container.encodeIfPresent(lastFailureAt, forKey: .lastFailureAt)
    }
}

