//
// LatencyTrendResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LatencyTrendResponse: Codable, JSONEncodable, Hashable {

    public var range: String?
    public var buckets: [LatencyTrendResponseBucketsInner]?
    public var overallAvgMs: Double?

    public init(range: String? = nil, buckets: [LatencyTrendResponseBucketsInner]? = nil, overallAvgMs: Double? = nil) {
        self.range = range
        self.buckets = buckets
        self.overallAvgMs = overallAvgMs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case range
        case buckets
        case overallAvgMs = "overall_avg_ms"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(range, forKey: .range)
        try container.encodeIfPresent(buckets, forKey: .buckets)
        try container.encodeIfPresent(overallAvgMs, forKey: .overallAvgMs)
    }
}

