//
// PlaygroundGet200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PlaygroundGet200Response: Codable, JSONEncodable, Hashable {

    public var endpoints: [AnyCodable]?
    public var samplePayloads: [AnyCodable]?

    public init(endpoints: [AnyCodable]? = nil, samplePayloads: [AnyCodable]? = nil) {
        self.endpoints = endpoints
        self.samplePayloads = samplePayloads
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case endpoints
        case samplePayloads = "sample_payloads"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(endpoints, forKey: .endpoints)
        try container.encodeIfPresent(samplePayloads, forKey: .samplePayloads)
    }
}

