//
// PortalProfile.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PortalProfile: Codable, JSONEncodable, Hashable {

    public var id: UUID?
    public var email: String?
    public var name: String?
    public var plan: String?
    public var createdAt: Date?

    public init(id: UUID? = nil, email: String? = nil, name: String? = nil, plan: String? = nil, createdAt: Date? = nil) {
        self.id = id
        self.email = email
        self.name = name
        self.plan = plan
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case email
        case name
        case plan
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(plan, forKey: .plan)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension PortalProfile: Identifiable {}
