//
// RegisterRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RegisterRequest: Codable, JSONEncodable, Hashable {

    public static let passwordRule = StringRule(minLength: 8, maxLength: nil, pattern: nil)
    public var email: String
    public var password: String?
    public var name: String?

    public init(email: String, password: String? = nil, name: String? = nil) {
        self.email = email
        self.password = password
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case password
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encodeIfPresent(password, forKey: .password)
        try container.encodeIfPresent(name, forKey: .name)
    }
}

