//
// RegisterDeviceRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RegisterDeviceRequest: Codable, JSONEncodable, Hashable {

    public enum Platform: String, Codable, CaseIterable {
        case android = "android"
        case ios = "ios"
        case web = "web"
    }
    /** FCM device token */
    public var token: String
    public var platform: Platform?

    public init(token: String, platform: Platform? = nil) {
        self.token = token
        self.platform = platform
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case token
        case platform
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(token, forKey: .token)
        try container.encodeIfPresent(platform, forKey: .platform)
    }
}

