//
// SimulatorPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SimulatorPostRequest: Codable, JSONEncodable, Hashable {

    public var endpointId: String?
    public var event: String?
    public var data: AnyCodable?

    public init(endpointId: String? = nil, event: String? = nil, data: AnyCodable? = nil) {
        self.endpointId = endpointId
        self.event = event
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case endpointId = "endpoint_id"
        case event
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(endpointId, forKey: .endpointId)
        try container.encodeIfPresent(event, forKey: .event)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

