//
// SsoConfigPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SsoConfigPostRequest: Codable, JSONEncodable, Hashable {

    public enum Provider: String, Codable, CaseIterable {
        case saml = "saml"
        case oidc = "oidc"
    }
    public var provider: Provider?
    public var enabled: Bool?

    public init(provider: Provider? = nil, enabled: Bool? = nil) {
        self.provider = provider
        self.enabled = enabled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case provider
        case enabled
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(provider, forKey: .provider)
        try container.encodeIfPresent(enabled, forKey: .enabled)
    }
}

