//
// StatsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StatsResponse: Codable, JSONEncodable, Hashable {

    public var totalDeliveries: Int?
    public var successfulDeliveries: Int?
    public var failedDeliveries: Int?
    public var totalEndpoints: Int?
    public var activeEndpoints: Int?
    public var plan: String?
    public var webhookLimit: Int?
    public var webhookCount: Int?

    public init(totalDeliveries: Int? = nil, successfulDeliveries: Int? = nil, failedDeliveries: Int? = nil, totalEndpoints: Int? = nil, activeEndpoints: Int? = nil, plan: String? = nil, webhookLimit: Int? = nil, webhookCount: Int? = nil) {
        self.totalDeliveries = totalDeliveries
        self.successfulDeliveries = successfulDeliveries
        self.failedDeliveries = failedDeliveries
        self.totalEndpoints = totalEndpoints
        self.activeEndpoints = activeEndpoints
        self.plan = plan
        self.webhookLimit = webhookLimit
        self.webhookCount = webhookCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case totalDeliveries = "total_deliveries"
        case successfulDeliveries = "successful_deliveries"
        case failedDeliveries = "failed_deliveries"
        case totalEndpoints = "total_endpoints"
        case activeEndpoints = "active_endpoints"
        case plan
        case webhookLimit = "webhook_limit"
        case webhookCount = "webhook_count"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(totalDeliveries, forKey: .totalDeliveries)
        try container.encodeIfPresent(successfulDeliveries, forKey: .successfulDeliveries)
        try container.encodeIfPresent(failedDeliveries, forKey: .failedDeliveries)
        try container.encodeIfPresent(totalEndpoints, forKey: .totalEndpoints)
        try container.encodeIfPresent(activeEndpoints, forKey: .activeEndpoints)
        try container.encodeIfPresent(plan, forKey: .plan)
        try container.encodeIfPresent(webhookLimit, forKey: .webhookLimit)
        try container.encodeIfPresent(webhookCount, forKey: .webhookCount)
    }
}

