//
// SubscriptionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SubscriptionResponse: Codable, JSONEncodable, Hashable {

    public var plan: String?
    public var status: String?
    public var paymentProvider: String?
    public var webhookLimit: Int?
    public var endpointLimit: Int?
    public var retentionDays: Int?
    public var monthlyPriceCents: Int?

    public init(plan: String? = nil, status: String? = nil, paymentProvider: String? = nil, webhookLimit: Int? = nil, endpointLimit: Int? = nil, retentionDays: Int? = nil, monthlyPriceCents: Int? = nil) {
        self.plan = plan
        self.status = status
        self.paymentProvider = paymentProvider
        self.webhookLimit = webhookLimit
        self.endpointLimit = endpointLimit
        self.retentionDays = retentionDays
        self.monthlyPriceCents = monthlyPriceCents
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case plan
        case status
        case paymentProvider = "payment_provider"
        case webhookLimit = "webhook_limit"
        case endpointLimit = "endpoint_limit"
        case retentionDays = "retention_days"
        case monthlyPriceCents = "monthly_price_cents"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(plan, forKey: .plan)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(paymentProvider, forKey: .paymentProvider)
        try container.encodeIfPresent(webhookLimit, forKey: .webhookLimit)
        try container.encodeIfPresent(endpointLimit, forKey: .endpointLimit)
        try container.encodeIfPresent(retentionDays, forKey: .retentionDays)
        try container.encodeIfPresent(monthlyPriceCents, forKey: .monthlyPriceCents)
    }
}

