//
// TeamInvite.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TeamInvite: Codable, JSONEncodable, Hashable {

    public var id: UUID?
    public var email: String?
    public var role: String?
    public var createdAt: Date?

    public init(id: UUID? = nil, email: String? = nil, role: String? = nil, createdAt: Date? = nil) {
        self.id = id
        self.email = email
        self.role = role
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case email
        case role
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(role, forKey: .role)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension TeamInvite: Identifiable {}
