//
// TestWebhookResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TestWebhookResponse: Codable, JSONEncodable, Hashable {

    public var success: Bool?
    public var statusCode: Int?
    public var durationMs: Int?
    public var responseBody: String?

    public init(success: Bool? = nil, statusCode: Int? = nil, durationMs: Int? = nil, responseBody: String? = nil) {
        self.success = success
        self.statusCode = statusCode
        self.durationMs = durationMs
        self.responseBody = responseBody
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case statusCode = "status_code"
        case durationMs = "duration_ms"
        case responseBody = "response_body"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(success, forKey: .success)
        try container.encodeIfPresent(statusCode, forKey: .statusCode)
        try container.encodeIfPresent(durationMs, forKey: .durationMs)
        try container.encodeIfPresent(responseBody, forKey: .responseBody)
    }
}

