//
// UpgradeRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpgradeRequest: Codable, JSONEncodable, Hashable {

    public enum Plan: String, Codable, CaseIterable {
        case pro = "pro"
        case business = "business"
    }
    public enum Provider: String, Codable, CaseIterable {
        case stripe = "stripe"
        case polar = "polar"
        case iyzico = "iyzico"
    }
    public var plan: Plan
    public var provider: Provider?

    public init(plan: Plan, provider: Provider? = nil) {
        self.plan = plan
        self.provider = provider
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case plan
        case provider
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(plan, forKey: .plan)
        try container.encodeIfPresent(provider, forKey: .provider)
    }
}

