//
// ValidateEventRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ValidateEventRequest: Codable, JSONEncodable, Hashable {

    public var event: AnyCodable

    public init(event: AnyCodable) {
        self.event = event
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case event
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(event, forKey: .event)
    }
}

