//
// WebhookTemplate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WebhookTemplate: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var name: String?
    public var description: String?
    public var category: String?
    public var payloadTemplate: AnyCodable?

    public init(id: String? = nil, name: String? = nil, description: String? = nil, category: String? = nil, payloadTemplate: AnyCodable? = nil) {
        self.id = id
        self.name = name
        self.description = description
        self.category = category
        self.payloadTemplate = payloadTemplate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case description
        case category
        case payloadTemplate = "payload_template"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(category, forKey: .category)
        try container.encodeIfPresent(payloadTemplate, forKey: .payloadTemplate)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension WebhookTemplate: Identifiable {}
