//
// AdminAuditEntry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A single admin audit log entry */
public struct AdminAuditEntry: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var customerId: UUID
    public var action: String
    public var resourceType: String
    public var resourceId: String?
    public var details: AnyCodable?
    public var ipAddress: String?
    public var userAgent: String?
    public var createdAt: Date

    public init(id: UUID, customerId: UUID, action: String, resourceType: String, resourceId: String? = nil, details: AnyCodable? = nil, ipAddress: String? = nil, userAgent: String? = nil, createdAt: Date) {
        self.id = id
        self.customerId = customerId
        self.action = action
        self.resourceType = resourceType
        self.resourceId = resourceId
        self.details = details
        self.ipAddress = ipAddress
        self.userAgent = userAgent
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case customerId = "customer_id"
        case action
        case resourceType = "resource_type"
        case resourceId = "resource_id"
        case details
        case ipAddress = "ip_address"
        case userAgent = "user_agent"
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(customerId, forKey: .customerId)
        try container.encode(action, forKey: .action)
        try container.encode(resourceType, forKey: .resourceType)
        try container.encodeIfPresent(resourceId, forKey: .resourceId)
        try container.encodeIfPresent(details, forKey: .details)
        try container.encodeIfPresent(ipAddress, forKey: .ipAddress)
        try container.encodeIfPresent(userAgent, forKey: .userAgent)
        try container.encode(createdAt, forKey: .createdAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension AdminAuditEntry: Identifiable {}
