//
// AdminTestWebhookRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Send a test HTTP POST to a URL (admin) */
public struct AdminTestWebhookRequest: Codable, JSONEncodable, Hashable {

    public var endpointUrl: String
    public var eventType: String?
    public var payload: AnyCodable

    public init(endpointUrl: String, eventType: String? = nil, payload: AnyCodable) {
        self.endpointUrl = endpointUrl
        self.eventType = eventType
        self.payload = payload
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case endpointUrl = "endpoint_url"
        case eventType = "event_type"
        case payload
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(endpointUrl, forKey: .endpointUrl)
        try container.encodeIfPresent(eventType, forKey: .eventType)
        try container.encode(payload, forKey: .payload)
    }
}

