//
// AdminUsersIdGet200ResponseRecentDeliveriesInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AdminUsersIdGet200ResponseRecentDeliveriesInner: Codable, JSONEncodable, Hashable {

    public var id: UUID?
    public var endpointId: UUID?
    public var status: String?
    public var eventType: String?
    public var createdAt: Date?
    public var attemptCount: Int?

    public init(id: UUID? = nil, endpointId: UUID? = nil, status: String? = nil, eventType: String? = nil, createdAt: Date? = nil, attemptCount: Int? = nil) {
        self.id = id
        self.endpointId = endpointId
        self.status = status
        self.eventType = eventType
        self.createdAt = createdAt
        self.attemptCount = attemptCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case endpointId = "endpoint_id"
        case status
        case eventType = "event_type"
        case createdAt = "created_at"
        case attemptCount = "attempt_count"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(endpointId, forKey: .endpointId)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(eventType, forKey: .eventType)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(attemptCount, forKey: .attemptCount)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension AdminUsersIdGet200ResponseRecentDeliveriesInner: Identifiable {}
