//
// AdminFeatureFlagsIdPutRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AdminFeatureFlagsIdPutRequest: Codable, JSONEncodable, Hashable {

    public static let rolloutPercentageRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 100, exclusiveMaximum: false, multipleOf: nil)
    public var name: String?
    public var description: String?
    public var isEnabled: Bool?
    public var rolloutPercentage: Int?
    public var enabledForPlans: [String]?

    public init(name: String? = nil, description: String? = nil, isEnabled: Bool? = nil, rolloutPercentage: Int? = nil, enabledForPlans: [String]? = nil) {
        self.name = name
        self.description = description
        self.isEnabled = isEnabled
        self.rolloutPercentage = rolloutPercentage
        self.enabledForPlans = enabledForPlans
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case description
        case isEnabled = "is_enabled"
        case rolloutPercentage = "rollout_percentage"
        case enabledForPlans = "enabled_for_plans"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(isEnabled, forKey: .isEnabled)
        try container.encodeIfPresent(rolloutPercentage, forKey: .rolloutPercentage)
        try container.encodeIfPresent(enabledForPlans, forKey: .enabledForPlans)
    }
}

