//
// AdminFeatureFlagsGet200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AdminFeatureFlagsGet200Response: Codable, JSONEncodable, Hashable {

    public var flags: [FeatureFlag]?

    public init(flags: [FeatureFlag]? = nil) {
        self.flags = flags
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case flags
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(flags, forKey: .flags)
    }
}

