//
// AdminRevenueGet200ResponseInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AdminRevenueGet200ResponseInner: Codable, JSONEncodable, Hashable {

    public var month: String?
    public var revenueCents: Int?
    public var subscriberCount: Int?

    public init(month: String? = nil, revenueCents: Int? = nil, subscriberCount: Int? = nil) {
        self.month = month
        self.revenueCents = revenueCents
        self.subscriberCount = subscriberCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case month
        case revenueCents = "revenue_cents"
        case subscriberCount = "subscriber_count"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(month, forKey: .month)
        try container.encodeIfPresent(revenueCents, forKey: .revenueCents)
        try container.encodeIfPresent(subscriberCount, forKey: .subscriberCount)
    }
}

