//
// AdminUpdateAlertRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Update an alert rule (admin, all fields optional) */
public struct AdminUpdateAlertRequest: Codable, JSONEncodable, Hashable {

    public enum Condition: String, Codable, CaseIterable {
        case failureRate = "failure_rate"
        case latency = "latency"
        case consecutiveFailures = "consecutive_failures"
    }
    public enum Channels: String, Codable, CaseIterable {
        case slack = "slack"
        case email = "email"
        case webhook = "webhook"
    }
    public var name: String?
    public var condition: Condition?
    public var threshold: Int?
    public var channels: [Channels]?
    public var isActive: Bool?

    public init(name: String? = nil, condition: Condition? = nil, threshold: Int? = nil, channels: [Channels]? = nil, isActive: Bool? = nil) {
        self.name = name
        self.condition = condition
        self.threshold = threshold
        self.channels = channels
        self.isActive = isActive
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case condition
        case threshold
        case channels
        case isActive = "is_active"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(condition, forKey: .condition)
        try container.encodeIfPresent(threshold, forKey: .threshold)
        try container.encodeIfPresent(channels, forKey: .channels)
        try container.encodeIfPresent(isActive, forKey: .isActive)
    }
}

