//
// AdminUsersIdGet200ResponseEndpointsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AdminUsersIdGet200ResponseEndpointsInner: Codable, JSONEncodable, Hashable {

    public var id: UUID?
    public var url: String?
    public var description: String?
    public var isActive: Bool?
    public var createdAt: Date?

    public init(id: UUID? = nil, url: String? = nil, description: String? = nil, isActive: Bool? = nil, createdAt: Date? = nil) {
        self.id = id
        self.url = url
        self.description = description
        self.isActive = isActive
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case url
        case description
        case isActive = "is_active"
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(isActive, forKey: .isActive)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension AdminUsersIdGet200ResponseEndpointsInner: Identifiable {}
