//
// AdminUsersIdGet200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AdminUsersIdGet200Response: Codable, JSONEncodable, Hashable {

    public var user: UserSummary?
    public var endpoints: [AdminUsersIdGet200ResponseEndpointsInner]?
    public var recentDeliveries: [AdminUsersIdGet200ResponseRecentDeliveriesInner]?
    public var usageStats: AdminUsersIdGet200ResponseUsageStats?

    public init(user: UserSummary? = nil, endpoints: [AdminUsersIdGet200ResponseEndpointsInner]? = nil, recentDeliveries: [AdminUsersIdGet200ResponseRecentDeliveriesInner]? = nil, usageStats: AdminUsersIdGet200ResponseUsageStats? = nil) {
        self.user = user
        self.endpoints = endpoints
        self.recentDeliveries = recentDeliveries
        self.usageStats = usageStats
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case user
        case endpoints
        case recentDeliveries = "recent_deliveries"
        case usageStats = "usage_stats"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(user, forKey: .user)
        try container.encodeIfPresent(endpoints, forKey: .endpoints)
        try container.encodeIfPresent(recentDeliveries, forKey: .recentDeliveries)
        try container.encodeIfPresent(usageStats, forKey: .usageStats)
    }
}

