//
// AdminRevenueResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Revenue history for admin analytics */
public struct AdminRevenueResponse: Codable, JSONEncodable, Hashable {

    public var data: [AdminRevenueEntry]
    /** Current total MRR across all subscriptions */
    public var totalMrr: Double

    public init(data: [AdminRevenueEntry], totalMrr: Double) {
        self.data = data
        self.totalMrr = totalMrr
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case totalMrr = "total_mrr"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(data, forKey: .data)
        try container.encode(totalMrr, forKey: .totalMrr)
    }
}

