//
// AdminTestWebhookResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Result of a test webhook delivery */
public struct AdminTestWebhookResponse: Codable, JSONEncodable, Hashable {

    public var statusCode: Int
    public var responseBody: String
    public var durationMs: Int

    public init(statusCode: Int, responseBody: String, durationMs: Int) {
        self.statusCode = statusCode
        self.responseBody = responseBody
        self.durationMs = durationMs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case statusCode = "status_code"
        case responseBody = "response_body"
        case durationMs = "duration_ms"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(statusCode, forKey: .statusCode)
        try container.encode(responseBody, forKey: .responseBody)
        try container.encode(durationMs, forKey: .durationMs)
    }
}

