//
// Application.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Application: Codable, JSONEncodable, Hashable {

    public var id: UUID?
    public var customerId: UUID?
    public var name: String?
    public var description: String?
    public var isActive: Bool?
    public var endpointCount: Int?
    public var createdAt: Date?
    public var updatedAt: Date?

    public init(id: UUID? = nil, customerId: UUID? = nil, name: String? = nil, description: String? = nil, isActive: Bool? = nil, endpointCount: Int? = nil, createdAt: Date? = nil, updatedAt: Date? = nil) {
        self.id = id
        self.customerId = customerId
        self.name = name
        self.description = description
        self.isActive = isActive
        self.endpointCount = endpointCount
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case customerId = "customer_id"
        case name
        case description
        case isActive = "is_active"
        case endpointCount = "endpoint_count"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(customerId, forKey: .customerId)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(isActive, forKey: .isActive)
        try container.encodeIfPresent(endpointCount, forKey: .endpointCount)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Application: Identifiable {}
