//
// ApplicationsIdPutRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ApplicationsIdPutRequest: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var description: String?
    public var isActive: Bool?

    public init(name: String? = nil, description: String? = nil, isActive: Bool? = nil) {
        self.name = name
        self.description = description
        self.isActive = isActive
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case description
        case isActive = "is_active"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(isActive, forKey: .isActive)
    }
}

