//
// AuthResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AuthResponse: Codable, JSONEncodable, Hashable {

    /** JWT access token */
    public var token: String
    public var customer: CustomerResponse
    /** Refresh token (when applicable) */
    public var refreshToken: String?

    public init(token: String, customer: CustomerResponse, refreshToken: String? = nil) {
        self.token = token
        self.customer = customer
        self.refreshToken = refreshToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case token
        case customer
        case refreshToken = "refresh_token"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(token, forKey: .token)
        try container.encode(customer, forKey: .customer)
        try container.encodeIfPresent(refreshToken, forKey: .refreshToken)
    }
}

