//
// AuthLoginPost200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum AuthLoginPost200Response: Codable, JSONEncodable, Hashable {
    case typeAuthResponse(AuthResponse)
    case typeTwoFactorRequiredResponse(TwoFactorRequiredResponse)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeAuthResponse(let value):
            try container.encode(value)
        case .typeTwoFactorRequiredResponse(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(AuthResponse.self) {
            self = .typeAuthResponse(value)
        } else if let value = try? container.decode(TwoFactorRequiredResponse.self) {
            self = .typeTwoFactorRequiredResponse(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of AuthLoginPost200Response"))
        }
    }
}

