//
// AuthConsentGet200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AuthConsentGet200Response: Codable, JSONEncodable, Hashable {

    public var consents: [String: Bool]?

    public init(consents: [String: Bool]? = nil) {
        self.consents = consents
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case consents
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(consents, forKey: .consents)
    }
}

