//
// BatchResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BatchResponse: Codable, JSONEncodable, Hashable {

    public var deliveries: [Delivery]
    public var errors: [BatchResponseErrorsInner]

    public init(deliveries: [Delivery], errors: [BatchResponseErrorsInner]) {
        self.deliveries = deliveries
        self.errors = errors
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case deliveries
        case errors
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(deliveries, forKey: .deliveries)
        try container.encode(errors, forKey: .errors)
    }
}

