//
// BatchWebhookResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Response for batch webhook delivery creation */
public struct BatchWebhookResponse: Codable, JSONEncodable, Hashable {

    /** List of created delivery IDs */
    public var deliveryIds: [UUID]
    /** Number of deliveries created */
    public var count: Int

    public init(deliveryIds: [UUID], count: Int) {
        self.deliveryIds = deliveryIds
        self.count = count
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case deliveryIds = "delivery_ids"
        case count
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(deliveryIds, forKey: .deliveryIds)
        try container.encode(count, forKey: .count)
    }
}

