//
// BatchResponseErrorsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BatchResponseErrorsInner: Codable, JSONEncodable, Hashable {

    public var index: Int?
    public var error: String?

    public init(index: Int? = nil, error: String? = nil) {
        self.index = index
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case index
        case error
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(index, forKey: .index)
        try container.encodeIfPresent(error, forKey: .error)
    }
}

