//
// BatchWebhookRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BatchWebhookRequest: Codable, JSONEncodable, Hashable {

    public var webhooks: [CreateWebhookRequest]

    public init(webhooks: [CreateWebhookRequest]) {
        self.webhooks = webhooks
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case webhooks
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(webhooks, forKey: .webhooks)
    }
}

