//
// CancelSubscriptionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Result of subscription cancellation */
public struct CancelSubscriptionResponse: Codable, JSONEncodable, Hashable {

    public var cancelledAt: Date
    public var endsAt: Date

    public init(cancelledAt: Date, endsAt: Date) {
        self.cancelledAt = cancelledAt
        self.endsAt = endsAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cancelledAt = "cancelled_at"
        case endsAt = "ends_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(cancelledAt, forKey: .cancelledAt)
        try container.encode(endsAt, forKey: .endsAt)
    }
}

