//
// ChurnedUser.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A user who churned (became inactive) recently */
public struct ChurnedUser: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var email: String
    public var name: String?
    public var plan: String
    public var amount: Double
    public var churnDate: Date

    public init(id: UUID, email: String, name: String? = nil, plan: String, amount: Double, churnDate: Date) {
        self.id = id
        self.email = email
        self.name = name
        self.plan = plan
        self.amount = amount
        self.churnDate = churnDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case email
        case name
        case plan
        case amount
        case churnDate = "churn_date"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(email, forKey: .email)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encode(plan, forKey: .plan)
        try container.encode(amount, forKey: .amount)
        try container.encode(churnDate, forKey: .churnDate)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ChurnedUser: Identifiable {}
