//
// CreateSSOConfigRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Create a new SSO configuration */
public struct CreateSSOConfigRequest: Codable, JSONEncodable, Hashable {

    public enum Provider: String, Codable, CaseIterable {
        case saml = "saml"
        case oidc = "oidc"
    }
    public var provider: Provider
    public var domain: String
    /** URL to SAML metadata or OIDC discovery document */
    public var metadataUrl: String

    public init(provider: Provider, domain: String, metadataUrl: String) {
        self.provider = provider
        self.domain = domain
        self.metadataUrl = metadataUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case provider
        case domain
        case metadataUrl = "metadata_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(provider, forKey: .provider)
        try container.encode(domain, forKey: .domain)
        try container.encode(metadataUrl, forKey: .metadataUrl)
    }
}

