//
// CreateCustomDomainRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Register a new custom domain */
public struct CreateCustomDomainRequest: Codable, JSONEncodable, Hashable {

    /** Fully qualified domain name to register */
    public var domain: String

    public init(domain: String) {
        self.domain = domain
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case domain
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(domain, forKey: .domain)
    }
}

