//
// CustomerResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CustomerResponse: Codable, JSONEncodable, Hashable {

    public enum Plan: String, Codable, CaseIterable {
        case free = "free"
        case pro = "pro"
        case business = "business"
    }
    public var id: UUID
    public var email: String
    public var name: String?
    /** Only returned on registration */
    public var apiKey: String?
    public var plan: Plan
    public var webhookLimit: Int
    public var webhookCount: Int
    public var isAdmin: Bool
    public var createdAt: Date

    public init(id: UUID, email: String, name: String? = nil, apiKey: String? = nil, plan: Plan, webhookLimit: Int, webhookCount: Int, isAdmin: Bool, createdAt: Date) {
        self.id = id
        self.email = email
        self.name = name
        self.apiKey = apiKey
        self.plan = plan
        self.webhookLimit = webhookLimit
        self.webhookCount = webhookCount
        self.isAdmin = isAdmin
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case email
        case name
        case apiKey = "api_key"
        case plan
        case webhookLimit = "webhook_limit"
        case webhookCount = "webhook_count"
        case isAdmin = "is_admin"
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(email, forKey: .email)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(apiKey, forKey: .apiKey)
        try container.encode(plan, forKey: .plan)
        try container.encode(webhookLimit, forKey: .webhookLimit)
        try container.encode(webhookCount, forKey: .webhookCount)
        try container.encode(isAdmin, forKey: .isAdmin)
        try container.encode(createdAt, forKey: .createdAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension CustomerResponse: Identifiable {}
