//
// DailyDeliveryCount.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Daily delivery count breakdown */
public struct DailyDeliveryCount: Codable, JSONEncodable, Hashable {

    public var date: Date
    public var total: Int
    public var success: Int
    public var failed: Int

    public init(date: Date, total: Int, success: Int, failed: Int) {
        self.date = date
        self.total = total
        self.success = success
        self.failed = failed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case date
        case total
        case success
        case failed
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(date, forKey: .date)
        try container.encode(total, forKey: .total)
        try container.encode(success, forKey: .success)
        try container.encode(failed, forKey: .failed)
    }
}

