//
// DeliveryAttempt.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DeliveryAttempt: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var attemptNumber: Int
    public var statusCode: Int?
    public var responseBody: String?
    public var durationMs: Int?
    public var errorMessage: String?
    public var createdAt: Date

    public init(id: UUID, attemptNumber: Int, statusCode: Int? = nil, responseBody: String? = nil, durationMs: Int? = nil, errorMessage: String? = nil, createdAt: Date) {
        self.id = id
        self.attemptNumber = attemptNumber
        self.statusCode = statusCode
        self.responseBody = responseBody
        self.durationMs = durationMs
        self.errorMessage = errorMessage
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case attemptNumber = "attempt_number"
        case statusCode = "status_code"
        case responseBody = "response_body"
        case durationMs = "duration_ms"
        case errorMessage = "error_message"
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(attemptNumber, forKey: .attemptNumber)
        try container.encodeIfPresent(statusCode, forKey: .statusCode)
        try container.encodeIfPresent(responseBody, forKey: .responseBody)
        try container.encodeIfPresent(durationMs, forKey: .durationMs)
        try container.encodeIfPresent(errorMessage, forKey: .errorMessage)
        try container.encode(createdAt, forKey: .createdAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension DeliveryAttempt: Identifiable {}
