//
// DeliveryTrendResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DeliveryTrendResponse: Codable, JSONEncodable, Hashable {

    public var range: String
    public var buckets: [DeliveryTrendResponseBucketsInner]

    public init(range: String, buckets: [DeliveryTrendResponseBucketsInner]) {
        self.range = range
        self.buckets = buckets
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case range
        case buckets
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(range, forKey: .range)
        try container.encode(buckets, forKey: .buckets)
    }
}

