//
// DeliveryDetailResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Full delivery detail including all retry attempts and endpoint info */
public struct DeliveryDetailResponse: Codable, JSONEncodable, Hashable {

    public var delivery: Delivery
    public var attempts: [DeliveryAttempt]
    public var endpoint: Endpoint?
    /** Original request headers sent with the delivery */
    public var requestHeaders: AnyCodable?
    /** Original request body sent with the delivery */
    public var requestBody: AnyCodable?
    /** Response headers received from the endpoint */
    public var responseHeaders: AnyCodable?

    public init(delivery: Delivery, attempts: [DeliveryAttempt], endpoint: Endpoint? = nil, requestHeaders: AnyCodable? = nil, requestBody: AnyCodable? = nil, responseHeaders: AnyCodable? = nil) {
        self.delivery = delivery
        self.attempts = attempts
        self.endpoint = endpoint
        self.requestHeaders = requestHeaders
        self.requestBody = requestBody
        self.responseHeaders = responseHeaders
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case delivery
        case attempts
        case endpoint
        case requestHeaders = "request_headers"
        case requestBody = "request_body"
        case responseHeaders = "response_headers"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(delivery, forKey: .delivery)
        try container.encode(attempts, forKey: .attempts)
        try container.encodeIfPresent(endpoint, forKey: .endpoint)
        try container.encodeIfPresent(requestHeaders, forKey: .requestHeaders)
        try container.encodeIfPresent(requestBody, forKey: .requestBody)
        try container.encodeIfPresent(responseHeaders, forKey: .responseHeaders)
    }
}

