//
// Delivery.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Delivery: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable {
        case pending = "pending"
        case processing = "processing"
        case delivered = "delivered"
        case failed = "failed"
    }
    public var id: UUID
    public var endpointId: UUID
    public var event: String?
    public var status: Status
    public var attemptCount: Int
    public var responseStatus: Int?
    public var replayCount: Int
    public var createdAt: Date

    public init(id: UUID, endpointId: UUID, event: String? = nil, status: Status, attemptCount: Int, responseStatus: Int? = nil, replayCount: Int, createdAt: Date) {
        self.id = id
        self.endpointId = endpointId
        self.event = event
        self.status = status
        self.attemptCount = attemptCount
        self.responseStatus = responseStatus
        self.replayCount = replayCount
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case endpointId = "endpoint_id"
        case event
        case status
        case attemptCount = "attempt_count"
        case responseStatus = "response_status"
        case replayCount = "replay_count"
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(endpointId, forKey: .endpointId)
        try container.encodeIfPresent(event, forKey: .event)
        try container.encode(status, forKey: .status)
        try container.encode(attemptCount, forKey: .attemptCount)
        try container.encodeIfPresent(responseStatus, forKey: .responseStatus)
        try container.encode(replayCount, forKey: .replayCount)
        try container.encode(createdAt, forKey: .createdAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Delivery: Identifiable {}
