//
// DeliveryTrendResponseBucketsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DeliveryTrendResponseBucketsInner: Codable, JSONEncodable, Hashable {

    public var timestamp: String?
    public var successful: Int?
    public var failed: Int?
    public var total: Int?

    public init(timestamp: String? = nil, successful: Int? = nil, failed: Int? = nil, total: Int? = nil) {
        self.timestamp = timestamp
        self.successful = successful
        self.failed = failed
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case timestamp
        case successful
        case failed
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encodeIfPresent(successful, forKey: .successful)
        try container.encodeIfPresent(failed, forKey: .failed)
        try container.encodeIfPresent(total, forKey: .total)
    }
}

