//
// DeviceTokenResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DeviceTokenResponse: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var token: String
    public var platform: String
    public var createdAt: Date

    public init(id: UUID, token: String, platform: String, createdAt: Date) {
        self.id = id
        self.token = token
        self.platform = platform
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case token
        case platform
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(token, forKey: .token)
        try container.encode(platform, forKey: .platform)
        try container.encode(createdAt, forKey: .createdAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension DeviceTokenResponse: Identifiable {}
