//
// EmbedConfigTheme.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Visual customization for the embed */
public struct EmbedConfigTheme: Codable, JSONEncodable, Hashable {

    public var primaryColor: String?
    public var backgroundColor: String?
    public var fontFamily: String?

    public init(primaryColor: String? = nil, backgroundColor: String? = nil, fontFamily: String? = nil) {
        self.primaryColor = primaryColor
        self.backgroundColor = backgroundColor
        self.fontFamily = fontFamily
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case primaryColor = "primary_color"
        case backgroundColor = "background_color"
        case fontFamily = "font_family"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(primaryColor, forKey: .primaryColor)
        try container.encodeIfPresent(backgroundColor, forKey: .backgroundColor)
        try container.encodeIfPresent(fontFamily, forKey: .fontFamily)
    }
}

