//
// EmbedConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Configuration for embedded webhook dashboard */
public struct EmbedConfig: Codable, JSONEncodable, Hashable {

    /** CORS origins allowed to load the embed */
    public var allowedOrigins: [String]
    public var theme: EmbedConfigTheme?
    /** Enabled features (e.g. [deliveries, endpoints, playground]) */
    public var features: [String]?

    public init(allowedOrigins: [String], theme: EmbedConfigTheme? = nil, features: [String]? = nil) {
        self.allowedOrigins = allowedOrigins
        self.theme = theme
        self.features = features
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case allowedOrigins = "allowed_origins"
        case theme
        case features
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(allowedOrigins, forKey: .allowedOrigins)
        try container.encodeIfPresent(theme, forKey: .theme)
        try container.encodeIfPresent(features, forKey: .features)
    }
}

