//
// EndpointsEndpointIdTransformsTestPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EndpointsEndpointIdTransformsTestPostRequest: Codable, JSONEncodable, Hashable {

    public var payload: AnyCodable?
    public var ruleId: UUID?

    public init(payload: AnyCodable? = nil, ruleId: UUID? = nil) {
        self.payload = payload
        self.ruleId = ruleId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case payload
        case ruleId = "rule_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(payload, forKey: .payload)
        try container.encodeIfPresent(ruleId, forKey: .ruleId)
    }
}

