//
// EndpointHealth.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Endpoint health metrics and status */
public struct EndpointHealth: Codable, JSONEncodable, Hashable {

    public var endpointId: UUID
    public var isHealthy: Bool
    public var failureStreak: Int?
    public var avgResponseMs: Int?
    public var lastFailureAt: Date?
    /** Success rate as a fraction (0.0–1.0) */
    public var successRate: Double?
    /** Average delivery latency in milliseconds */
    public var avgLatencyMs: Double?
    public var lastDeliveryAt: Date?
    public var totalDeliveries: Int?
    public var failedDeliveries: Int?

    public init(endpointId: UUID, isHealthy: Bool, failureStreak: Int? = nil, avgResponseMs: Int? = nil, lastFailureAt: Date? = nil, successRate: Double? = nil, avgLatencyMs: Double? = nil, lastDeliveryAt: Date? = nil, totalDeliveries: Int? = nil, failedDeliveries: Int? = nil) {
        self.endpointId = endpointId
        self.isHealthy = isHealthy
        self.failureStreak = failureStreak
        self.avgResponseMs = avgResponseMs
        self.lastFailureAt = lastFailureAt
        self.successRate = successRate
        self.avgLatencyMs = avgLatencyMs
        self.lastDeliveryAt = lastDeliveryAt
        self.totalDeliveries = totalDeliveries
        self.failedDeliveries = failedDeliveries
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case endpointId = "endpoint_id"
        case isHealthy = "is_healthy"
        case failureStreak = "failure_streak"
        case avgResponseMs = "avg_response_ms"
        case lastFailureAt = "last_failure_at"
        case successRate = "success_rate"
        case avgLatencyMs = "avg_latency_ms"
        case lastDeliveryAt = "last_delivery_at"
        case totalDeliveries = "total_deliveries"
        case failedDeliveries = "failed_deliveries"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(endpointId, forKey: .endpointId)
        try container.encode(isHealthy, forKey: .isHealthy)
        try container.encodeIfPresent(failureStreak, forKey: .failureStreak)
        try container.encodeIfPresent(avgResponseMs, forKey: .avgResponseMs)
        try container.encodeIfPresent(lastFailureAt, forKey: .lastFailureAt)
        try container.encodeIfPresent(successRate, forKey: .successRate)
        try container.encodeIfPresent(avgLatencyMs, forKey: .avgLatencyMs)
        try container.encodeIfPresent(lastDeliveryAt, forKey: .lastDeliveryAt)
        try container.encodeIfPresent(totalDeliveries, forKey: .totalDeliveries)
        try container.encodeIfPresent(failedDeliveries, forKey: .failedDeliveries)
    }
}

