//
// EndpointsIdRotateSecretPost200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EndpointsIdRotateSecretPost200Response: Codable, JSONEncodable, Hashable {

    public var signingSecret: String?
    public var message: String?

    public init(signingSecret: String? = nil, message: String? = nil) {
        self.signingSecret = signingSecret
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case signingSecret = "signing_secret"
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(signingSecret, forKey: .signingSecret)
        try container.encodeIfPresent(message, forKey: .message)
    }
}

