//
// EventTypeCount.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Event type occurrence count */
public struct EventTypeCount: Codable, JSONEncodable, Hashable {

    public var event: String?
    public var count: Int

    public init(event: String? = nil, count: Int) {
        self.event = event
        self.count = count
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case event
        case count
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(event, forKey: .event)
        try container.encode(count, forKey: .count)
    }
}

