//
// InboundConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct InboundConfig: Codable, JSONEncodable, Hashable {

    public var id: UUID?
    public var customerId: UUID?
    /** Provider name (stripe, github, shopify, generic) */
    public var provider: String?
    /** Webhook signing secret */
    public var secret: String?
    public var endpointId: UUID?
    public var enabled: Bool?
    public var createdAt: Date?

    public init(id: UUID? = nil, customerId: UUID? = nil, provider: String? = nil, secret: String? = nil, endpointId: UUID? = nil, enabled: Bool? = nil, createdAt: Date? = nil) {
        self.id = id
        self.customerId = customerId
        self.provider = provider
        self.secret = secret
        self.endpointId = endpointId
        self.enabled = enabled
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case customerId = "customer_id"
        case provider
        case secret
        case endpointId = "endpoint_id"
        case enabled
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(customerId, forKey: .customerId)
        try container.encodeIfPresent(provider, forKey: .provider)
        try container.encodeIfPresent(secret, forKey: .secret)
        try container.encodeIfPresent(endpointId, forKey: .endpointId)
        try container.encodeIfPresent(enabled, forKey: .enabled)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension InboundConfig: Identifiable {}
