//
// InboundConfigsIdPutRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct InboundConfigsIdPutRequest: Codable, JSONEncodable, Hashable {

    public var secret: String?
    public var endpointId: UUID?
    public var enabled: Bool?

    public init(secret: String? = nil, endpointId: UUID? = nil, enabled: Bool? = nil) {
        self.secret = secret
        self.endpointId = endpointId
        self.enabled = enabled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case secret
        case endpointId = "endpoint_id"
        case enabled
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(secret, forKey: .secret)
        try container.encodeIfPresent(endpointId, forKey: .endpointId)
        try container.encodeIfPresent(enabled, forKey: .enabled)
    }
}

