//
// InboundWebhookRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Raw webhook payload received from an external provider (Stripe, GitHub, etc.) */
public struct InboundWebhookRequest: Codable, JSONEncodable, Hashable {

    /** Provider name (e.g. stripe, github, shopify) */
    public var provider: String
    /** Raw webhook payload body */
    public var payload: AnyCodable
    /** HTTP headers from the incoming webhook request */
    public var headers: AnyCodable?

    public init(provider: String, payload: AnyCodable, headers: AnyCodable? = nil) {
        self.provider = provider
        self.payload = payload
        self.headers = headers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case provider
        case payload
        case headers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(provider, forKey: .provider)
        try container.encode(payload, forKey: .payload)
        try container.encodeIfPresent(headers, forKey: .headers)
    }
}

