//
// InboundConfigsPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct InboundConfigsPostRequest: Codable, JSONEncodable, Hashable {

    /** Provider name (stripe, github, shopify, generic) */
    public var provider: String
    /** Webhook signing secret */
    public var secret: String
    /** Default target endpoint */
    public var endpointId: UUID?
    public var enabled: Bool? = true

    public init(provider: String, secret: String, endpointId: UUID? = nil, enabled: Bool? = true) {
        self.provider = provider
        self.secret = secret
        self.endpointId = endpointId
        self.enabled = enabled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case provider
        case secret
        case endpointId = "endpoint_id"
        case enabled
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(provider, forKey: .provider)
        try container.encode(secret, forKey: .secret)
        try container.encodeIfPresent(endpointId, forKey: .endpointId)
        try container.encodeIfPresent(enabled, forKey: .enabled)
    }
}

