//
// InvoiceResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct InvoiceResponse: Codable, JSONEncodable, Hashable {

    public var id: String
    public var amountCents: Int64
    public var currency: String
    public var status: String
    public var createdAt: Date

    public init(id: String, amountCents: Int64, currency: String, status: String, createdAt: Date) {
        self.id = id
        self.amountCents = amountCents
        self.currency = currency
        self.status = status
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case amountCents = "amount_cents"
        case currency
        case status
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(amountCents, forKey: .amountCents)
        try container.encode(currency, forKey: .currency)
        try container.encode(status, forKey: .status)
        try container.encode(createdAt, forKey: .createdAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension InvoiceResponse: Identifiable {}
