//
// LatencyResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Latency percentile breakdown for deliveries */
public struct LatencyResponse: Codable, JSONEncodable, Hashable {

    public enum Period: String, Codable, CaseIterable {
        case _24h = "24h"
        case _7d = "7d"
        case _30d = "30d"
    }
    /** 50th percentile (median) latency in ms */
    public var p50: Float
    /** 90th percentile latency in ms */
    public var p90: Float
    /** 95th percentile latency in ms */
    public var p95: Float
    /** 99th percentile latency in ms */
    public var p99: Float
    /** Time range of the data */
    public var period: Period

    public init(p50: Float, p90: Float, p95: Float, p99: Float, period: Period) {
        self.p50 = p50
        self.p90 = p90
        self.p95 = p95
        self.p99 = p99
        self.period = period
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case p50
        case p90
        case p95
        case p99
        case period
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(p50, forKey: .p50)
        try container.encode(p90, forKey: .p90)
        try container.encode(p95, forKey: .p95)
        try container.encode(p99, forKey: .p99)
        try container.encode(period, forKey: .period)
    }
}

