//
// NotificationPreferences.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NotificationPreferences: Codable, JSONEncodable, Hashable {

    public var emailOnFailure: Bool = true
    public var emailOnDeadLetter: Bool = true
    public var emailOnSuccess: Bool = false
    public var slackWebhookUrl: String?
    public var discordWebhookUrl: String?
    public var webhookUrl: String?

    public init(emailOnFailure: Bool = true, emailOnDeadLetter: Bool = true, emailOnSuccess: Bool = false, slackWebhookUrl: String? = nil, discordWebhookUrl: String? = nil, webhookUrl: String? = nil) {
        self.emailOnFailure = emailOnFailure
        self.emailOnDeadLetter = emailOnDeadLetter
        self.emailOnSuccess = emailOnSuccess
        self.slackWebhookUrl = slackWebhookUrl
        self.discordWebhookUrl = discordWebhookUrl
        self.webhookUrl = webhookUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case emailOnFailure = "email_on_failure"
        case emailOnDeadLetter = "email_on_dead_letter"
        case emailOnSuccess = "email_on_success"
        case slackWebhookUrl = "slack_webhook_url"
        case discordWebhookUrl = "discord_webhook_url"
        case webhookUrl = "webhook_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(emailOnFailure, forKey: .emailOnFailure)
        try container.encode(emailOnDeadLetter, forKey: .emailOnDeadLetter)
        try container.encode(emailOnSuccess, forKey: .emailOnSuccess)
        try container.encodeIfPresent(slackWebhookUrl, forKey: .slackWebhookUrl)
        try container.encodeIfPresent(discordWebhookUrl, forKey: .discordWebhookUrl)
        try container.encodeIfPresent(webhookUrl, forKey: .webhookUrl)
    }
}

