//
// Notification.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Notification: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var title: String
    public var body: String
    public var isRead: Bool
    public var link: String?
    public var createdAt: Date

    public init(id: UUID, title: String, body: String, isRead: Bool, link: String? = nil, createdAt: Date) {
        self.id = id
        self.title = title
        self.body = body
        self.isRead = isRead
        self.link = link
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case title
        case body
        case isRead = "is_read"
        case link
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(title, forKey: .title)
        try container.encode(body, forKey: .body)
        try container.encode(isRead, forKey: .isRead)
        try container.encodeIfPresent(link, forKey: .link)
        try container.encode(createdAt, forKey: .createdAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Notification: Identifiable {}
