//
// NotificationListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NotificationListResponse: Codable, JSONEncodable, Hashable {

    public var notifications: [Notification]
    public var total: Int
    public var unreadCount: Int

    public init(notifications: [Notification], total: Int, unreadCount: Int) {
        self.notifications = notifications
        self.total = total
        self.unreadCount = unreadCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case notifications
        case total
        case unreadCount = "unread_count"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(notifications, forKey: .notifications)
        try container.encode(total, forKey: .total)
        try container.encode(unreadCount, forKey: .unreadCount)
    }
}

