//
// OAuthLoginRedirect.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** OAuth redirect information */
public struct OAuthLoginRedirect: Codable, JSONEncodable, Hashable {

    public var redirectUrl: String

    public init(redirectUrl: String) {
        self.redirectUrl = redirectUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case redirectUrl = "redirect_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(redirectUrl, forKey: .redirectUrl)
    }
}

