//
// OAuthCallbackRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** OAuth authorization callback parameters */
public struct OAuthCallbackRequest: Codable, JSONEncodable, Hashable {

    /** Authorization code from the provider */
    public var code: String
    /** CSRF state token */
    public var state: String
    public var redirectUri: String?

    public init(code: String, state: String, redirectUri: String? = nil) {
        self.code = code
        self.state = state
        self.redirectUri = redirectUri
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case state
        case redirectUri = "redirect_uri"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(code, forKey: .code)
        try container.encode(state, forKey: .state)
        try container.encodeIfPresent(redirectUri, forKey: .redirectUri)
    }
}

