//
// OutboundIPsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** List of static outbound IP addresses for firewall whitelisting */
public struct OutboundIPsResponse: Codable, JSONEncodable, Hashable {

    /** IPv4 and IPv6 addresses used for outbound requests */
    public var ips: [String]

    public init(ips: [String]) {
        self.ips = ips
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ips
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ips, forKey: .ips)
    }
}

