//
// OutboundIpsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OutboundIpsResponse: Codable, JSONEncodable, Hashable {

    public var ips: [String]?
    public var updatedAt: String?

    public init(ips: [String]? = nil, updatedAt: String? = nil) {
        self.ips = ips
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ips
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(ips, forKey: .ips)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}

