//
// PaginatedUsers.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PaginatedUsers: Codable, JSONEncodable, Hashable {

    public var users: [UserSummary]
    public var total: Int
    public var page: Int
    public var perPage: Int

    public init(users: [UserSummary], total: Int, page: Int, perPage: Int) {
        self.users = users
        self.total = total
        self.page = page
        self.perPage = perPage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case users
        case total
        case page
        case perPage = "per_page"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(users, forKey: .users)
        try container.encode(total, forKey: .total)
        try container.encode(page, forKey: .page)
        try container.encode(perPage, forKey: .perPage)
    }
}

