//
// PlatformSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Platform-wide configuration settings */
public struct PlatformSettings: Codable, JSONEncodable, Hashable {

    public var defaultPlan: String
    public var maxEndpointsFree: Int
    public var maxEndpointsPro: Int
    public var maxWebhooksFree: Int
    public var maxWebhooksPro: Int
    public var rateLimitFree: Int
    public var rateLimitPro: Int
    public var retryMaxAttempts: Int
    public var retentionDaysFree: Int
    public var retentionDaysPro: Int
    public var maintenanceMode: Bool
    public var signupEnabled: Bool
    public var planPricePro: Double
    public var planPriceBusiness: Double
    public var resendApiKey: String?
    public var emailSender: String?

    public init(defaultPlan: String, maxEndpointsFree: Int, maxEndpointsPro: Int, maxWebhooksFree: Int, maxWebhooksPro: Int, rateLimitFree: Int, rateLimitPro: Int, retryMaxAttempts: Int, retentionDaysFree: Int, retentionDaysPro: Int, maintenanceMode: Bool, signupEnabled: Bool, planPricePro: Double, planPriceBusiness: Double, resendApiKey: String? = nil, emailSender: String? = nil) {
        self.defaultPlan = defaultPlan
        self.maxEndpointsFree = maxEndpointsFree
        self.maxEndpointsPro = maxEndpointsPro
        self.maxWebhooksFree = maxWebhooksFree
        self.maxWebhooksPro = maxWebhooksPro
        self.rateLimitFree = rateLimitFree
        self.rateLimitPro = rateLimitPro
        self.retryMaxAttempts = retryMaxAttempts
        self.retentionDaysFree = retentionDaysFree
        self.retentionDaysPro = retentionDaysPro
        self.maintenanceMode = maintenanceMode
        self.signupEnabled = signupEnabled
        self.planPricePro = planPricePro
        self.planPriceBusiness = planPriceBusiness
        self.resendApiKey = resendApiKey
        self.emailSender = emailSender
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case defaultPlan = "default_plan"
        case maxEndpointsFree = "max_endpoints_free"
        case maxEndpointsPro = "max_endpoints_pro"
        case maxWebhooksFree = "max_webhooks_free"
        case maxWebhooksPro = "max_webhooks_pro"
        case rateLimitFree = "rate_limit_free"
        case rateLimitPro = "rate_limit_pro"
        case retryMaxAttempts = "retry_max_attempts"
        case retentionDaysFree = "retention_days_free"
        case retentionDaysPro = "retention_days_pro"
        case maintenanceMode = "maintenance_mode"
        case signupEnabled = "signup_enabled"
        case planPricePro = "plan_price_pro"
        case planPriceBusiness = "plan_price_business"
        case resendApiKey = "resend_api_key"
        case emailSender = "email_sender"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(defaultPlan, forKey: .defaultPlan)
        try container.encode(maxEndpointsFree, forKey: .maxEndpointsFree)
        try container.encode(maxEndpointsPro, forKey: .maxEndpointsPro)
        try container.encode(maxWebhooksFree, forKey: .maxWebhooksFree)
        try container.encode(maxWebhooksPro, forKey: .maxWebhooksPro)
        try container.encode(rateLimitFree, forKey: .rateLimitFree)
        try container.encode(rateLimitPro, forKey: .rateLimitPro)
        try container.encode(retryMaxAttempts, forKey: .retryMaxAttempts)
        try container.encode(retentionDaysFree, forKey: .retentionDaysFree)
        try container.encode(retentionDaysPro, forKey: .retentionDaysPro)
        try container.encode(maintenanceMode, forKey: .maintenanceMode)
        try container.encode(signupEnabled, forKey: .signupEnabled)
        try container.encode(planPricePro, forKey: .planPricePro)
        try container.encode(planPriceBusiness, forKey: .planPriceBusiness)
        try container.encodeIfPresent(resendApiKey, forKey: .resendApiKey)
        try container.encodeIfPresent(emailSender, forKey: .emailSender)
    }
}

