//
// PortalConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Customer-facing portal branding and configuration */
public struct PortalConfig: Codable, JSONEncodable, Hashable {

    public var logoUrl: String?
    /** Hex color code (e.g. */
    public var primaryColor: String?
    public var customDomain: String?
    /** Event types to expose in the portal */
    public var webhookEvents: [String]?

    public init(logoUrl: String? = nil, primaryColor: String? = nil, customDomain: String? = nil, webhookEvents: [String]? = nil) {
        self.logoUrl = logoUrl
        self.primaryColor = primaryColor
        self.customDomain = customDomain
        self.webhookEvents = webhookEvents
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case logoUrl = "logo_url"
        case primaryColor = "primary_color"
        case customDomain = "custom_domain"
        case webhookEvents = "webhook_events"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(logoUrl, forKey: .logoUrl)
        try container.encodeIfPresent(primaryColor, forKey: .primaryColor)
        try container.encodeIfPresent(customDomain, forKey: .customDomain)
        try container.encodeIfPresent(webhookEvents, forKey: .webhookEvents)
    }
}

