//
// PortalNotificationsPut200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PortalNotificationsPut200Response: Codable, JSONEncodable, Hashable {

    public var updated: Bool?
    public var preferences: NotificationPreferences?

    public init(updated: Bool? = nil, preferences: NotificationPreferences? = nil) {
        self.updated = updated
        self.preferences = preferences
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case updated
        case preferences
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(updated, forKey: .updated)
        try container.encodeIfPresent(preferences, forKey: .preferences)
    }
}

