//
// RateLimitUsage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Current rate limit usage for an endpoint */
public struct RateLimitUsage: Codable, JSONEncodable, Hashable {

    /** Current requests per second being consumed */
    public var currentRps: Double
    /** Configured requests per second limit */
    public var limitRps: Double
    /** Remaining capacity */
    public var remaining: Double
    public var resetAt: Date

    public init(currentRps: Double, limitRps: Double, remaining: Double, resetAt: Date) {
        self.currentRps = currentRps
        self.limitRps = limitRps
        self.remaining = remaining
        self.resetAt = resetAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case currentRps = "current_rps"
        case limitRps = "limit_rps"
        case remaining
        case resetAt = "reset_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(currentRps, forKey: .currentRps)
        try container.encode(limitRps, forKey: .limitRps)
        try container.encode(remaining, forKey: .remaining)
        try container.encode(resetAt, forKey: .resetAt)
    }
}

