//
// RateLimitConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Rate limiting configuration for an endpoint */
public struct RateLimitConfig: Codable, JSONEncodable, Hashable {

    /** Maximum requests per second allowed */
    public var requestsPerSecond: Int
    /** Maximum burst above steady-state rate */
    public var burstSize: Int
    public var enabled: Bool

    public init(requestsPerSecond: Int, burstSize: Int, enabled: Bool) {
        self.requestsPerSecond = requestsPerSecond
        self.burstSize = burstSize
        self.enabled = enabled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case requestsPerSecond = "requests_per_second"
        case burstSize = "burst_size"
        case enabled
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requestsPerSecond, forKey: .requestsPerSecond)
        try container.encode(burstSize, forKey: .burstSize)
        try container.encode(enabled, forKey: .enabled)
    }
}

