//
// RegisterSchemaRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RegisterSchemaRequest: Codable, JSONEncodable, Hashable {

    public var name: String
    /** JSON Schema document */
    public var schema: AnyCodable

    public init(name: String, schema: AnyCodable) {
        self.name = name
        self.schema = schema
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case schema
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(schema, forKey: .schema)
    }
}

