//
// ReplayDeliveryResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Result of replaying a delivery */
public struct ReplayDeliveryResponse: Codable, JSONEncodable, Hashable {

    public var message: String
    public var originalId: UUID
    public var newDeliveryId: UUID

    public init(message: String, originalId: UUID, newDeliveryId: UUID) {
        self.message = message
        self.originalId = originalId
        self.newDeliveryId = newDeliveryId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case originalId = "original_id"
        case newDeliveryId = "new_delivery_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(message, forKey: .message)
        try container.encode(originalId, forKey: .originalId)
        try container.encode(newDeliveryId, forKey: .newDeliveryId)
    }
}

