//
// ResetPasswordRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ResetPasswordRequest: Codable, JSONEncodable, Hashable {

    public static let newPasswordRule = StringRule(minLength: 8, maxLength: nil, pattern: nil)
    public var token: String
    public var newPassword: String

    public init(token: String, newPassword: String) {
        self.token = token
        self.newPassword = newPassword
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case token
        case newPassword = "new_password"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(token, forKey: .token)
        try container.encode(newPassword, forKey: .newPassword)
    }
}

