//
// RevenueResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Full revenue analytics response */
public struct RevenueResponse: Codable, JSONEncodable, Hashable {

    public var monthlyRevenue: [RevenueResponseMonthlyRevenueInner]
    public var revenueByPlan: [RevenueResponseRevenueByPlanInner]
    public var mrr: Double
    public var churnRate: Double
    public var mrrTrend: Double

    public init(monthlyRevenue: [RevenueResponseMonthlyRevenueInner], revenueByPlan: [RevenueResponseRevenueByPlanInner], mrr: Double, churnRate: Double, mrrTrend: Double) {
        self.monthlyRevenue = monthlyRevenue
        self.revenueByPlan = revenueByPlan
        self.mrr = mrr
        self.churnRate = churnRate
        self.mrrTrend = mrrTrend
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case monthlyRevenue = "monthly_revenue"
        case revenueByPlan = "revenue_by_plan"
        case mrr
        case churnRate = "churn_rate"
        case mrrTrend = "mrr_trend"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(monthlyRevenue, forKey: .monthlyRevenue)
        try container.encode(revenueByPlan, forKey: .revenueByPlan)
        try container.encode(mrr, forKey: .mrr)
        try container.encode(churnRate, forKey: .churnRate)
        try container.encode(mrrTrend, forKey: .mrrTrend)
    }
}

