//
// SchemaListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Paginated list of registered schemas */
public struct SchemaListResponse: Codable, JSONEncodable, Hashable {

    public var data: [SchemaResponse]
    public var hasMore: Bool
    public var total: Int

    public init(data: [SchemaResponse], hasMore: Bool, total: Int) {
        self.data = data
        self.hasMore = hasMore
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case hasMore = "has_more"
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(data, forKey: .data)
        try container.encode(hasMore, forKey: .hasMore)
        try container.encode(total, forKey: .total)
    }
}

