//
// SearchResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SearchResult: Codable, JSONEncodable, Hashable {

    public var deliveries: [Delivery]
    public var total: Int

    public init(deliveries: [Delivery], total: Int) {
        self.deliveries = deliveries
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case deliveries
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(deliveries, forKey: .deliveries)
        try container.encode(total, forKey: .total)
    }
}

