//
// SearchRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Search request for webhook deliveries */
public struct SearchRequest: Codable, JSONEncodable, Hashable {

    /** Search query string */
    public var query: String
    public var filters: SearchRequestFilters?
    public var page: Int? = 1
    public var perPage: Int? = 20

    public init(query: String, filters: SearchRequestFilters? = nil, page: Int? = 1, perPage: Int? = 20) {
        self.query = query
        self.filters = filters
        self.page = page
        self.perPage = perPage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case query
        case filters
        case page
        case perPage = "per_page"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(query, forKey: .query)
        try container.encodeIfPresent(filters, forKey: .filters)
        try container.encodeIfPresent(page, forKey: .page)
        try container.encodeIfPresent(perPage, forKey: .perPage)
    }
}

