//
// SearchRequestFilters.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Additional filters (status, endpoint_id, etc.) */
public struct SearchRequestFilters: Codable, JSONEncodable, Hashable {

    public var status: String?
    public var endpointId: UUID?

    public init(status: String? = nil, endpointId: UUID? = nil) {
        self.status = status
        self.endpointId = endpointId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case endpointId = "endpoint_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(endpointId, forKey: .endpointId)
    }
}

