//
// ServiceToken.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceToken: Codable, JSONEncodable, Hashable {

    public var id: UUID?
    public var name: String?
    /** Token prefix (first 24 chars + ...) */
    public var tokenPrefix: String?
    public var createdAt: Date?
    public var lastUsedAt: Date?
    public var isActive: Bool?

    public init(id: UUID? = nil, name: String? = nil, tokenPrefix: String? = nil, createdAt: Date? = nil, lastUsedAt: Date? = nil, isActive: Bool? = nil) {
        self.id = id
        self.name = name
        self.tokenPrefix = tokenPrefix
        self.createdAt = createdAt
        self.lastUsedAt = lastUsedAt
        self.isActive = isActive
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case tokenPrefix = "token_prefix"
        case createdAt = "created_at"
        case lastUsedAt = "last_used_at"
        case isActive = "is_active"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(tokenPrefix, forKey: .tokenPrefix)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(lastUsedAt, forKey: .lastUsedAt)
        try container.encodeIfPresent(isActive, forKey: .isActive)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ServiceToken: Identifiable {}
