//
// SimulatorRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Send a simulated webhook event */
public struct SimulatorRequest: Codable, JSONEncodable, Hashable {

    public var endpointId: UUID
    /** Event type to simulate (e.g. order.created) */
    public var eventType: String
    /** The webhook payload to deliver */
    public var payload: AnyCodable
    /** Artificial delay before delivery (for testing timeouts) */
    public var delayMs: Int?

    public init(endpointId: UUID, eventType: String, payload: AnyCodable, delayMs: Int? = nil) {
        self.endpointId = endpointId
        self.eventType = eventType
        self.payload = payload
        self.delayMs = delayMs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case endpointId = "endpoint_id"
        case eventType = "event_type"
        case payload
        case delayMs = "delay_ms"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(endpointId, forKey: .endpointId)
        try container.encode(eventType, forKey: .eventType)
        try container.encode(payload, forKey: .payload)
        try container.encodeIfPresent(delayMs, forKey: .delayMs)
    }
}

