//
// SimulatorResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Result of a simulated webhook delivery */
public struct SimulatorResponse: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable {
        case delivered = "delivered"
        case failed = "failed"
        case pending = "pending"
    }
    public var deliveryId: UUID
    public var status: Status
    /** Response time from the endpoint */
    public var latencyMs: Int

    public init(deliveryId: UUID, status: Status, latencyMs: Int) {
        self.deliveryId = deliveryId
        self.status = status
        self.latencyMs = latencyMs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case deliveryId = "delivery_id"
        case status
        case latencyMs = "latency_ms"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(deliveryId, forKey: .deliveryId)
        try container.encode(status, forKey: .status)
        try container.encode(latencyMs, forKey: .latencyMs)
    }
}

