//
// SSOConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Single Sign-On configuration (SAML or OIDC) */
public struct SSOConfig: Codable, JSONEncodable, Hashable {

    public enum Provider: String, Codable, CaseIterable {
        case saml = "saml"
        case oidc = "oidc"
    }
    public var provider: Provider
    /** Email domain for SSO routing */
    public var domain: String
    /** SAML entity ID or OIDC issuer */
    public var entityId: String?
    public var ssoUrl: String?
    /** PEM-encoded X.509 certificate (SAML) */
    public var certificate: String?

    public init(provider: Provider, domain: String, entityId: String? = nil, ssoUrl: String? = nil, certificate: String? = nil) {
        self.provider = provider
        self.domain = domain
        self.entityId = entityId
        self.ssoUrl = ssoUrl
        self.certificate = certificate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case provider
        case domain
        case entityId = "entity_id"
        case ssoUrl = "sso_url"
        case certificate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(provider, forKey: .provider)
        try container.encode(domain, forKey: .domain)
        try container.encodeIfPresent(entityId, forKey: .entityId)
        try container.encodeIfPresent(ssoUrl, forKey: .ssoUrl)
        try container.encodeIfPresent(certificate, forKey: .certificate)
    }
}

