//
// StatsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StatsResponse: Codable, JSONEncodable, Hashable {

    public var totalDeliveries: Int
    public var successfulDeliveries: Int
    public var failedDeliveries: Int
    public var totalEndpoints: Int
    public var activeEndpoints: Int
    public var plan: String
    public var webhookLimit: Int
    public var webhookCount: Int

    public init(totalDeliveries: Int, successfulDeliveries: Int, failedDeliveries: Int, totalEndpoints: Int, activeEndpoints: Int, plan: String, webhookLimit: Int, webhookCount: Int) {
        self.totalDeliveries = totalDeliveries
        self.successfulDeliveries = successfulDeliveries
        self.failedDeliveries = failedDeliveries
        self.totalEndpoints = totalEndpoints
        self.activeEndpoints = activeEndpoints
        self.plan = plan
        self.webhookLimit = webhookLimit
        self.webhookCount = webhookCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case totalDeliveries = "total_deliveries"
        case successfulDeliveries = "successful_deliveries"
        case failedDeliveries = "failed_deliveries"
        case totalEndpoints = "total_endpoints"
        case activeEndpoints = "active_endpoints"
        case plan
        case webhookLimit = "webhook_limit"
        case webhookCount = "webhook_count"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(totalDeliveries, forKey: .totalDeliveries)
        try container.encode(successfulDeliveries, forKey: .successfulDeliveries)
        try container.encode(failedDeliveries, forKey: .failedDeliveries)
        try container.encode(totalEndpoints, forKey: .totalEndpoints)
        try container.encode(activeEndpoints, forKey: .activeEndpoints)
        try container.encode(plan, forKey: .plan)
        try container.encode(webhookLimit, forKey: .webhookLimit)
        try container.encode(webhookCount, forKey: .webhookCount)
    }
}

