//
// SubscriptionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SubscriptionResponse: Codable, JSONEncodable, Hashable {

    public var plan: String
    public var status: String
    public var paymentProvider: String
    public var webhookLimit: Int
    public var endpointLimit: Int
    public var retentionDays: Int
    public var monthlyPriceCents: Int

    public init(plan: String, status: String, paymentProvider: String, webhookLimit: Int, endpointLimit: Int, retentionDays: Int, monthlyPriceCents: Int) {
        self.plan = plan
        self.status = status
        self.paymentProvider = paymentProvider
        self.webhookLimit = webhookLimit
        self.endpointLimit = endpointLimit
        self.retentionDays = retentionDays
        self.monthlyPriceCents = monthlyPriceCents
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case plan
        case status
        case paymentProvider = "payment_provider"
        case webhookLimit = "webhook_limit"
        case endpointLimit = "endpoint_limit"
        case retentionDays = "retention_days"
        case monthlyPriceCents = "monthly_price_cents"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(plan, forKey: .plan)
        try container.encode(status, forKey: .status)
        try container.encode(paymentProvider, forKey: .paymentProvider)
        try container.encode(webhookLimit, forKey: .webhookLimit)
        try container.encode(endpointLimit, forKey: .endpointLimit)
        try container.encode(retentionDays, forKey: .retentionDays)
        try container.encode(monthlyPriceCents, forKey: .monthlyPriceCents)
    }
}

