//
// SuccessRateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SuccessRateResponse: Codable, JSONEncodable, Hashable {

    public var range: String
    public var successful: Int
    public var failed: Int
    public var pending: Int
    public var successRate: Double

    public init(range: String, successful: Int, failed: Int, pending: Int, successRate: Double) {
        self.range = range
        self.successful = successful
        self.failed = failed
        self.pending = pending
        self.successRate = successRate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case range
        case successful
        case failed
        case pending
        case successRate = "success_rate"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(range, forKey: .range)
        try container.encode(successful, forKey: .successful)
        try container.encode(failed, forKey: .failed)
        try container.encode(pending, forKey: .pending)
        try container.encode(successRate, forKey: .successRate)
    }
}

