//
// SystemStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SystemStatus: Codable, JSONEncodable, Hashable {

    public enum OverallStatus: String, Codable, CaseIterable {
        case operational = "operational"
        case degraded = "degraded"
        case down = "down"
    }
    public var overallStatus: OverallStatus
    public var uptime30d: Double
    public var components: [SystemStatusComponentsInner]
    public var checkedAt: String

    public init(overallStatus: OverallStatus, uptime30d: Double, components: [SystemStatusComponentsInner], checkedAt: String) {
        self.overallStatus = overallStatus
        self.uptime30d = uptime30d
        self.components = components
        self.checkedAt = checkedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case overallStatus = "overall_status"
        case uptime30d = "uptime_30d"
        case components
        case checkedAt = "checked_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(overallStatus, forKey: .overallStatus)
        try container.encode(uptime30d, forKey: .uptime30d)
        try container.encode(components, forKey: .components)
        try container.encode(checkedAt, forKey: .checkedAt)
    }
}

