//
// SystemStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SystemStats: Codable, JSONEncodable, Hashable {

    public var totalUsers: Int
    public var activeUsers: Int
    public var totalEndpoints: Int
    public var totalDeliveries: Int
    public var planBreakdown: [SystemStatsPlanBreakdownInner]

    public init(totalUsers: Int, activeUsers: Int, totalEndpoints: Int, totalDeliveries: Int, planBreakdown: [SystemStatsPlanBreakdownInner]) {
        self.totalUsers = totalUsers
        self.activeUsers = activeUsers
        self.totalEndpoints = totalEndpoints
        self.totalDeliveries = totalDeliveries
        self.planBreakdown = planBreakdown
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case totalUsers = "total_users"
        case activeUsers = "active_users"
        case totalEndpoints = "total_endpoints"
        case totalDeliveries = "total_deliveries"
        case planBreakdown = "plan_breakdown"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(totalUsers, forKey: .totalUsers)
        try container.encode(activeUsers, forKey: .activeUsers)
        try container.encode(totalEndpoints, forKey: .totalEndpoints)
        try container.encode(totalDeliveries, forKey: .totalDeliveries)
        try container.encode(planBreakdown, forKey: .planBreakdown)
    }
}

