//
// SystemStatusComponentsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SystemStatusComponentsInner: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var status: String?
    public var latencyMs: Int?
    public var description: String?
    public var lastChecked: String?

    public init(name: String? = nil, status: String? = nil, latencyMs: Int? = nil, description: String? = nil, lastChecked: String? = nil) {
        self.name = name
        self.status = status
        self.latencyMs = latencyMs
        self.description = description
        self.lastChecked = lastChecked
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case status
        case latencyMs = "latency_ms"
        case description
        case lastChecked = "last_checked"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(latencyMs, forKey: .latencyMs)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(lastChecked, forKey: .lastChecked)
    }
}

