//
// TeamMember.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TeamMember: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var userId: UUID
    public var email: String
    public var name: String?
    public var role: String
    public var joinedAt: Date

    public init(id: UUID, userId: UUID, email: String, name: String? = nil, role: String, joinedAt: Date) {
        self.id = id
        self.userId = userId
        self.email = email
        self.name = name
        self.role = role
        self.joinedAt = joinedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case userId = "user_id"
        case email
        case name
        case role
        case joinedAt = "joined_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(userId, forKey: .userId)
        try container.encode(email, forKey: .email)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encode(role, forKey: .role)
        try container.encode(joinedAt, forKey: .joinedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension TeamMember: Identifiable {}
