//
// TestWebhookRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TestWebhookRequest: Codable, JSONEncodable, Hashable {

    public var endpointId: UUID
    public var payload: AnyCodable
    public var event: String?

    public init(endpointId: UUID, payload: AnyCodable, event: String? = nil) {
        self.endpointId = endpointId
        self.payload = payload
        self.event = event
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case endpointId = "endpoint_id"
        case payload
        case event
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(endpointId, forKey: .endpointId)
        try container.encode(payload, forKey: .payload)
        try container.encodeIfPresent(event, forKey: .event)
    }
}

