//
// TransformRule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TransformRule: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var endpointId: UUID
    public var name: String
    public var ruleType: String
    public var config: AnyCodable?
    public var isActive: Bool
    public var createdAt: Date

    public init(id: UUID, endpointId: UUID, name: String, ruleType: String, config: AnyCodable? = nil, isActive: Bool, createdAt: Date) {
        self.id = id
        self.endpointId = endpointId
        self.name = name
        self.ruleType = ruleType
        self.config = config
        self.isActive = isActive
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case endpointId = "endpoint_id"
        case name
        case ruleType = "rule_type"
        case config
        case isActive = "is_active"
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(endpointId, forKey: .endpointId)
        try container.encode(name, forKey: .name)
        try container.encode(ruleType, forKey: .ruleType)
        try container.encodeIfPresent(config, forKey: .config)
        try container.encode(isActive, forKey: .isActive)
        try container.encode(createdAt, forKey: .createdAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension TransformRule: Identifiable {}
