//
// UpdateSSOConfigRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Update an SSO configuration (all fields optional) */
public struct UpdateSSOConfigRequest: Codable, JSONEncodable, Hashable {

    public enum Provider: String, Codable, CaseIterable {
        case saml = "saml"
        case oidc = "oidc"
    }
    public var provider: Provider
    public var domain: String

    public init(provider: Provider, domain: String) {
        self.provider = provider
        self.domain = domain
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case provider
        case domain
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(provider, forKey: .provider)
        try container.encode(domain, forKey: .domain)
    }
}

