//
// UpdateTransformRuleRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Update an existing transform rule (all fields optional) */
public struct UpdateTransformRuleRequest: Codable, JSONEncodable, Hashable {

    public var name: String
    /** Updated transformation configuration */
    public var config: AnyCodable?

    public init(name: String, config: AnyCodable? = nil) {
        self.name = name
        self.config = config
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case config
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(config, forKey: .config)
    }
}

