//
// UpdateRoutingRuleRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Update an existing routing rule (all fields optional) */
public struct UpdateRoutingRuleRequest: Codable, JSONEncodable, Hashable {

    public var name: String
    public var conditions: AnyCodable?
    public var transform: AnyCodable?

    public init(name: String, conditions: AnyCodable? = nil, transform: AnyCodable? = nil) {
        self.name = name
        self.conditions = conditions
        self.transform = transform
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case conditions
        case transform
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(conditions, forKey: .conditions)
        try container.encodeIfPresent(transform, forKey: .transform)
    }
}

