//
// UpdateRoutingRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateRoutingRequest: Codable, JSONEncodable, Hashable {

    public enum RoutingStrategy: String, Codable, CaseIterable {
        case roundRobin = "round-robin"
        case latency = "latency"
        case failover = "failover"
    }
    public var routingStrategy: RoutingStrategy
    public var fallbackUrl: String

    public init(routingStrategy: RoutingStrategy, fallbackUrl: String) {
        self.routingStrategy = routingStrategy
        self.fallbackUrl = fallbackUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case routingStrategy = "routing_strategy"
        case fallbackUrl = "fallback_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(routingStrategy, forKey: .routingStrategy)
        try container.encode(fallbackUrl, forKey: .fallbackUrl)
    }
}

