//
// UpdateAlertRuleRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Request to update an existing alert rule (all fields optional) */
public struct UpdateAlertRuleRequest: Codable, JSONEncodable, Hashable {

    public enum Condition: String, Codable, CaseIterable {
        case failureRate = "failure_rate"
        case latency = "latency"
        case consecutiveFailures = "consecutive_failures"
    }
    public enum Channels: String, Codable, CaseIterable {
        case slack = "slack"
        case email = "email"
        case webhook = "webhook"
    }
    public var name: String
    public var condition: Condition
    public var threshold: Int
    public var channels: [Channels]

    public init(name: String, condition: Condition, threshold: Int, channels: [Channels]) {
        self.name = name
        self.condition = condition
        self.threshold = threshold
        self.channels = channels
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case condition
        case threshold
        case channels
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(condition, forKey: .condition)
        try container.encode(threshold, forKey: .threshold)
        try container.encode(channels, forKey: .channels)
    }
}

