//
// UpdateEndpointRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateEndpointRequest: Codable, JSONEncodable, Hashable {

    public enum RoutingStrategy: String, Codable, CaseIterable {
        case roundRobin = "round-robin"
        case latency = "latency"
        case failover = "failover"
    }
    public enum Format: String, Codable, CaseIterable {
        case standard = "standard"
        case cloudevents = "cloudevents"
    }
    public var url: String
    public var description: String
    public var isActive: Bool
    public var allowedIps: [String]
    public var eventFilter: [String]
    public var customHeaders: AnyCodable?
    public var retryPolicy: RetryPolicy
    public var routingStrategy: RoutingStrategy
    public var fallbackUrl: String
    public var format: Format

    public init(url: String, description: String, isActive: Bool, allowedIps: [String], eventFilter: [String], customHeaders: AnyCodable? = nil, retryPolicy: RetryPolicy, routingStrategy: RoutingStrategy, fallbackUrl: String, format: Format) {
        self.url = url
        self.description = description
        self.isActive = isActive
        self.allowedIps = allowedIps
        self.eventFilter = eventFilter
        self.customHeaders = customHeaders
        self.retryPolicy = retryPolicy
        self.routingStrategy = routingStrategy
        self.fallbackUrl = fallbackUrl
        self.format = format
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case url
        case description
        case isActive = "is_active"
        case allowedIps = "allowed_ips"
        case eventFilter = "event_filter"
        case customHeaders = "custom_headers"
        case retryPolicy = "retry_policy"
        case routingStrategy = "routing_strategy"
        case fallbackUrl = "fallback_url"
        case format
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(url, forKey: .url)
        try container.encode(description, forKey: .description)
        try container.encode(isActive, forKey: .isActive)
        try container.encode(allowedIps, forKey: .allowedIps)
        try container.encode(eventFilter, forKey: .eventFilter)
        try container.encodeIfPresent(customHeaders, forKey: .customHeaders)
        try container.encode(retryPolicy, forKey: .retryPolicy)
        try container.encode(routingStrategy, forKey: .routingStrategy)
        try container.encode(fallbackUrl, forKey: .fallbackUrl)
        try container.encode(format, forKey: .format)
    }
}

