//
// UpgradeResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpgradeResponse: Codable, JSONEncodable, Hashable {

    public var checkoutUrl: String?
    public var provider: String
    public var message: String

    public init(checkoutUrl: String? = nil, provider: String, message: String) {
        self.checkoutUrl = checkoutUrl
        self.provider = provider
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case checkoutUrl = "checkout_url"
        case provider
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(checkoutUrl, forKey: .checkoutUrl)
        try container.encode(provider, forKey: .provider)
        try container.encode(message, forKey: .message)
    }
}

