//
// UsageStatsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Account usage statistics summary */
public struct UsageStatsResponse: Codable, JSONEncodable, Hashable {

    /** Number of active endpoints */
    public var endpointsCount: Int
    /** Total deliveries in current period */
    public var deliveriesCount: Int
    /** Number of teams */
    public var teamsCount: Int
    /** Storage used in bytes */
    public var storageUsedBytes: Int

    public init(endpointsCount: Int, deliveriesCount: Int, teamsCount: Int, storageUsedBytes: Int) {
        self.endpointsCount = endpointsCount
        self.deliveriesCount = deliveriesCount
        self.teamsCount = teamsCount
        self.storageUsedBytes = storageUsedBytes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case endpointsCount = "endpoints_count"
        case deliveriesCount = "deliveries_count"
        case teamsCount = "teams_count"
        case storageUsedBytes = "storage_used_bytes"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(endpointsCount, forKey: .endpointsCount)
        try container.encode(deliveriesCount, forKey: .deliveriesCount)
        try container.encode(teamsCount, forKey: .teamsCount)
        try container.encode(storageUsedBytes, forKey: .storageUsedBytes)
    }
}

