//
// UsageResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UsageResponse: Codable, JSONEncodable, Hashable {

    public var plan: String
    public var periodStart: Date
    public var periodEnd: Date
    public var webhooksUsed: Int
    public var webhooksLimit: Int
    public var endpointsUsed: Int
    public var endpointsLimit: Int

    public init(plan: String, periodStart: Date, periodEnd: Date, webhooksUsed: Int, webhooksLimit: Int, endpointsUsed: Int, endpointsLimit: Int) {
        self.plan = plan
        self.periodStart = periodStart
        self.periodEnd = periodEnd
        self.webhooksUsed = webhooksUsed
        self.webhooksLimit = webhooksLimit
        self.endpointsUsed = endpointsUsed
        self.endpointsLimit = endpointsLimit
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case plan
        case periodStart = "period_start"
        case periodEnd = "period_end"
        case webhooksUsed = "webhooks_used"
        case webhooksLimit = "webhooks_limit"
        case endpointsUsed = "endpoints_used"
        case endpointsLimit = "endpoints_limit"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(plan, forKey: .plan)
        try container.encode(periodStart, forKey: .periodStart)
        try container.encode(periodEnd, forKey: .periodEnd)
        try container.encode(webhooksUsed, forKey: .webhooksUsed)
        try container.encode(webhooksLimit, forKey: .webhooksLimit)
        try container.encode(endpointsUsed, forKey: .endpointsUsed)
        try container.encode(endpointsLimit, forKey: .endpointsLimit)
    }
}

