//
// ValidateEventResponseErrorsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ValidateEventResponseErrorsInner: Codable, JSONEncodable, Hashable {

    /** JSON pointer to the failing field */
    public var path: String?
    /** Human-readable validation error */
    public var message: String?

    public init(path: String? = nil, message: String? = nil) {
        self.path = path
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case path
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(path, forKey: .path)
        try container.encodeIfPresent(message, forKey: .message)
    }
}

