//
// VerifyCustomDomainResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Result of domain verification attempt */
public struct VerifyCustomDomainResponse: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable {
        case verified = "verified"
        case pending = "pending"
        case failed = "failed"
    }
    public var status: Status
    /** DNS records that need to be configured */
    public var dnsRecords: [DomainDnsRecord]

    public init(status: Status, dnsRecords: [DomainDnsRecord]) {
        self.status = status
        self.dnsRecords = dnsRecords
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case dnsRecords = "dns_records"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(dnsRecords, forKey: .dnsRecords)
    }
}

