//
// PlaygroundAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class PlaygroundAPI {

    /**
     Get playground info (endpoints, sample payloads)
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func playgroundGet(apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: PlaygroundGet200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return playgroundGetWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get playground info (endpoints, sample payloads)
     - GET /playground
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - returns: RequestBuilder<PlaygroundGet200Response> 
     */
    open class func playgroundGetWithRequestBuilder() -> RequestBuilder<PlaygroundGet200Response> {
        let localVariablePath = "/playground"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PlaygroundGet200Response>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Test a webhook delivery
     
     - parameter testWebhookRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func playgroundTestPost(testWebhookRequest: TestWebhookRequest, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: TestWebhookResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return playgroundTestPostWithRequestBuilder(testWebhookRequest: testWebhookRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Test a webhook delivery
     - POST /playground/test
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter testWebhookRequest: (body)  
     - returns: RequestBuilder<TestWebhookResponse> 
     */
    open class func playgroundTestPostWithRequestBuilder(testWebhookRequest: TestWebhookRequest) -> RequestBuilder<TestWebhookResponse> {
        let localVariablePath = "/playground/test"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: testWebhookRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<TestWebhookResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
