//
// TransformsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class TransformsAPI {

    /**
     List transform rules for endpoint
     
     - parameter endpointId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func endpointsEndpointIdTransformsGet(endpointId: UUID, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: [TransformRule]?, _ error: Error?) -> Void)) -> RequestTask {
        return endpointsEndpointIdTransformsGetWithRequestBuilder(endpointId: endpointId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List transform rules for endpoint
     - GET /endpoints/{endpoint_id}/transforms
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter endpointId: (path)  
     - returns: RequestBuilder<[TransformRule]> 
     */
    open class func endpointsEndpointIdTransformsGetWithRequestBuilder(endpointId: UUID) -> RequestBuilder<[TransformRule]> {
        var localVariablePath = "/endpoints/{endpoint_id}/transforms"
        let endpointIdPreEscape = "\(APIHelper.mapValueToPathItem(endpointId))"
        let endpointIdPostEscape = endpointIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{endpoint_id}", with: endpointIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[TransformRule]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Delete transform rule
     
     - parameter endpointId: (path)  
     - parameter id: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func endpointsEndpointIdTransformsIdDelete(endpointId: UUID, id: UUID, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return endpointsEndpointIdTransformsIdDeleteWithRequestBuilder(endpointId: endpointId, id: id).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Delete transform rule
     - DELETE /endpoints/{endpoint_id}/transforms/{id}
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter endpointId: (path)  
     - parameter id: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func endpointsEndpointIdTransformsIdDeleteWithRequestBuilder(endpointId: UUID, id: UUID) -> RequestBuilder<Void> {
        var localVariablePath = "/endpoints/{endpoint_id}/transforms/{id}"
        let endpointIdPreEscape = "\(APIHelper.mapValueToPathItem(endpointId))"
        let endpointIdPostEscape = endpointIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{endpoint_id}", with: endpointIdPostEscape, options: .literal, range: nil)
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = OpenAPIClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Update transform rule
     
     - parameter endpointId: (path)  
     - parameter id: (path)  
     - parameter body: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func endpointsEndpointIdTransformsIdPut(endpointId: UUID, id: UUID, body: AnyCodable, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: TransformRule?, _ error: Error?) -> Void)) -> RequestTask {
        return endpointsEndpointIdTransformsIdPutWithRequestBuilder(endpointId: endpointId, id: id, body: body).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Update transform rule
     - PUT /endpoints/{endpoint_id}/transforms/{id}
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter endpointId: (path)  
     - parameter id: (path)  
     - parameter body: (body)  
     - returns: RequestBuilder<TransformRule> 
     */
    open class func endpointsEndpointIdTransformsIdPutWithRequestBuilder(endpointId: UUID, id: UUID, body: AnyCodable) -> RequestBuilder<TransformRule> {
        var localVariablePath = "/endpoints/{endpoint_id}/transforms/{id}"
        let endpointIdPreEscape = "\(APIHelper.mapValueToPathItem(endpointId))"
        let endpointIdPostEscape = endpointIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{endpoint_id}", with: endpointIdPostEscape, options: .literal, range: nil)
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<TransformRule>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Create transform rule
     
     - parameter endpointId: (path)  
     - parameter createTransformRuleRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func endpointsEndpointIdTransformsPost(endpointId: UUID, createTransformRuleRequest: CreateTransformRuleRequest, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: TransformRule?, _ error: Error?) -> Void)) -> RequestTask {
        return endpointsEndpointIdTransformsPostWithRequestBuilder(endpointId: endpointId, createTransformRuleRequest: createTransformRuleRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create transform rule
     - POST /endpoints/{endpoint_id}/transforms
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter endpointId: (path)  
     - parameter createTransformRuleRequest: (body)  
     - returns: RequestBuilder<TransformRule> 
     */
    open class func endpointsEndpointIdTransformsPostWithRequestBuilder(endpointId: UUID, createTransformRuleRequest: CreateTransformRuleRequest) -> RequestBuilder<TransformRule> {
        var localVariablePath = "/endpoints/{endpoint_id}/transforms"
        let endpointIdPreEscape = "\(APIHelper.mapValueToPathItem(endpointId))"
        let endpointIdPostEscape = endpointIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{endpoint_id}", with: endpointIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createTransformRuleRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<TransformRule>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Test a transform rule
     
     - parameter endpointId: (path)  
     - parameter endpointsEndpointIdTransformsTestPostRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func endpointsEndpointIdTransformsTestPost(endpointId: UUID, endpointsEndpointIdTransformsTestPostRequest: EndpointsEndpointIdTransformsTestPostRequest, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return endpointsEndpointIdTransformsTestPostWithRequestBuilder(endpointId: endpointId, endpointsEndpointIdTransformsTestPostRequest: endpointsEndpointIdTransformsTestPostRequest).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Test a transform rule
     - POST /endpoints/{endpoint_id}/transforms/test
     - Bearer Token:
       - type: http
       - name: BearerAuth
     - parameter endpointId: (path)  
     - parameter endpointsEndpointIdTransformsTestPostRequest: (body)  
     - returns: RequestBuilder<Void> 
     */
    open class func endpointsEndpointIdTransformsTestPostWithRequestBuilder(endpointId: UUID, endpointsEndpointIdTransformsTestPostRequest: EndpointsEndpointIdTransformsTestPostRequest) -> RequestBuilder<Void> {
        var localVariablePath = "/endpoints/{endpoint_id}/transforms/test"
        let endpointIdPreEscape = "\(APIHelper.mapValueToPathItem(endpointId))"
        let endpointIdPostEscape = endpointIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{endpoint_id}", with: endpointIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: endpointsEndpointIdTransformsTestPostRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = OpenAPIClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
